### ISSUE TITLE
A major bug found in pca calculating the means adjustment vector

### ISSUE THREAD

**Issue by tzeikob** [MKLab-ITI/multimedia-indexing#12]
Means vector must be equal to a vector where each component must be the average of the corresponding column components of the matrix A, instead we ended with a vector where each component is equal to the last row component divided by the number of samples. See more in [class](https://github.com/MKLab-ITI/multimedia-indexing/blob/master/src/main/java/gr/iti/mklab/visual/dimreduction/PCA.java) at row 146.

**Comment by lefman** [comment]
Indeed tz3ik, thanks! 
Hopefully, not performing mean subtraction does not necessarily lead to performance deterioration http://www.ulb.ac.be/di/map/yleborgn/pub/NPL_PCA_07.pdf.
