### ISSUE TITLE
Berkeley DB is too slow compared to recent DB engines

### ISSUE THREAD

**Issue by futurely** [MKLab-ITI/multimedia-indexing#2]
Symas's results showed that their LMDB is much faster than Berkeley DB, while InfluxDB proved that Facebook's RocksDB performed best overall.

Facebook RocksDB officially supports Java.
https://github.com/facebook/rocksdb/tree/master/java
https://github.com/facebook/rocksdb/wiki/RocksJava-Basics

```
<dependency>
    <groupId>org.rocksdb</groupId>
    <artifactId>rocksdbjni</artifactId>
    <version>3.9.1</version>
</dependency>
```

[Benchmarking LevelDB vs. RocksDB vs. HyperLevelDB vs. LMDB Performance for InfluxDB](http://influxdb.com/blog/2014/06/20/leveldb_vs_rocksdb_vs_hyperleveldb_vs_lmdb_performance.html)

[RocksDB Performance Benchmarks](https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks)

![image](https://cloud.githubusercontent.com/assets/9004594/7174765/509b5438-e43f-11e4-9660-2b1d45861725.png)

[Symas On-Disk Microbenchmark](http://symas.com/mdb/ondisk/)

[Symas In-Memory Microbenchmark](http://symas.com/mdb/inmem/)
- On disk, 4000 byte values, Physical Server
  ![image](https://cloud.githubusercontent.com/assets/9004594/7174681/284cce0e-e43e-11e4-981c-8eaa60b0742d.png)

![image](https://cloud.githubusercontent.com/assets/9004594/7174683/30bc4d08-e43e-11e4-9a13-9ad68a830573.png)
- In memory, larger data set
  ![image](https://cloud.githubusercontent.com/assets/9004594/7174685/44e87428-e43e-11e4-8682-56578017cdf4.png)

![image](https://cloud.githubusercontent.com/assets/9004594/7174688/4d8f44f8-e43e-11e4-812e-12f33bd6284e.png)
- In memory, small data set
  ![image](https://cloud.githubusercontent.com/assets/9004594/7174602/3dff65fa-e43d-11e4-808b-7893d30ca5f2.png)

![image](https://cloud.githubusercontent.com/assets/9004594/7174607/48fa5834-e43d-11e4-9e1f-91eb777730eb.png)

**Comment by hyc** [comment]
The InfluxDB results for LMDB are invalid as they didn't use the API correctly. Their blog used to link to Disqus where a long discussion thread carried on this point, but for some reason the blog doesn't link to it any more. Full story here https://disqus.com/home/discussion/influxdb/benchmarking_leveldb_vs_rocksdb_vs_hyperleveldb_vs_lmdb_performance_for_influxdb/

Note that they never followed through on their promise to republish with updated results.

**Comment by futurely** [comment]
![image](https://cloud.githubusercontent.com/assets/9004594/26384930/fbfed9b6-406e-11e7-9765-100fc81baa61.png)

https://github.com/caffe2/caffe2/tree/master/caffe2/db

**Comment by lfoutz** [comment]
Any working links to the original Symas tests?  The results for BDB look off, and I would like to know if they did not use the database correctly.

**Comment by hyc** [comment]
Apologies for the dead links. All of the benchmark reports are still linked from here https://symas.com/lmdb/technical/

All of the benchmark driver source code is available here https://github.com/hyc/leveldb/tree/benches/doc/bench

A newer rewrite of the benchmark driver is here https://github.com/LMDB/dbbench
