### ISSUE TITLE
The image names indexed in FolderIndexingMT may be incorrect

### ISSUE THREAD

**Issue by futurely** [MKLab-ITI/multimedia-indexing#8]
In `gr.iti.mklab.visual.examples.FolderIndexingMT`, the image names are incorrect if the original filenames contain more than one dot or don't end with ".jpg".

```
 if (imvr != null) {
        String name = imvr.getImageName();
        name = name.split("\\.")[0] + ".jpg";
        if (imvr.getExceptionMessage() == null) {
          // vectorization completed with success!s
          double[] vector = imvr.getImageVector();
          if (index.indexVector(name, vector)) {
```

In `gr.iti.mklab.visual.examples.UrlIndexingMT`, the image names are kept as what they are.

```
            if (imvr != null) {
                String name = imvr.getImageName();
                double[] vector = imvr.getImageVector();
                if (index.indexVector(name, vector)) {
```

**Comment by lefman** [comment]
Both classes mentioned above are intended to serve as examples (they reside in the examples package!) rather than general purpose indexing functions.
